### ISSUE TITLE
Invio emoticon meteo

### ISSUE THREAD

**Issue by ipersoft** [comune-desio/azuredesio#4]
Riguardo questo commit non funziona più l'invio dell'emoticon

https://github.com/comune-desio/azuredesio/commit/2c4b6a6b95f17ac89cb68d9555cbc888ae3a4195
@olistik

**Comment by ipersoft** [comment]
ora funge

**Comment by olistik** [comment]
Typo fixato da https://github.com/comune-desio/azuredesio/commit/dbe43f3075a6a1599cf9ba47629bb9af3ca6ac91
